name: mvelopes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  animated_text_kit: ^4.2.1
  hive_flutter: ^1.1.0
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0
  month_year_picker: ^0.1.0+3
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  flutter_slidable: ^1.3.2
  lottie: ^1.4.0
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_charts: ^20.2.40
  awesome_notifications: ^0.6.21
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.5
  flutter_local_notifications: ^9.5.3+1
  provider: ^6.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: any
  hive_generator: any

flutter:
  uses-material-design: true
  
  assets:
    - assets/image/
 
  fonts:
     - family: redhat
       fonts:
         - asset: assets/fonts/redhat.otf
     - family: sea
       fonts:
         - asset: assets/fonts/one.ttf
 